language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success:
    "curl --ftp-create-dirs -T ./build/libs/modid-1.0-universal.jar -u $FTP_USER:$FTP_PASSWORD ftp://penagw.in/modid-1.0-universal.jar"
