branches:
  except:
    - gh-pages

language: java
jdk:
  - oraclejdk7

before_install:
 - chmod +x gradlew
 - VERSION=$(($VERSION + 1))

install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success:$
    "for i in build/libs/* ; do curl --ftp-create-dirs -T $i -u $USER:$PWD ftp://penagw.in/../../var/www/files/ModularBuilds/$(echo $VERSION)/${i##*/} ; done"
